### ISSUE TITLE
Wrong documentation links in readme

### ISSUE THREAD

**Issue by Przecinit** [mikeaag/phpunit-3.5.15#1]
The documentation lead not to version 3.5 but to the latest release. There is no documentation on PHPunit site at the moment. Any ideas where to find it?

**Comment by mikeaag** [comment]
Hey,

I've done a quick search around and found a copy of the old docs in PDF form on Wayback Machine - https://web.archive.org/web/20130512120557/http://phpunit.de/manual/3.5/en/phpunit-book.pdf

Given how old this version of PHPUnit is though, I would highly recommend that you update to a version which is still supported - https://github.com/sebastianbergmann/phpunit

Cheers,
Mike

**Comment by Przecinit** [comment]
Thank you very much! 
This is for very old project and upgrade is probably not possible in existing environment.

Happy New Year,
Szymon
